refactor(resilience4j-vavr): Adapting to vavr separation changes.
Springboot3 brings in updated versions of resilience4j where vavr dependency is segregated under new project.

Error:
```
^
clouddriver/clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/model/CloudFoundryServerGroup.java:34: error: package io.vavr.collection does not exist
import io.vavr.collection.HashMap;
                         ^
clouddriver/clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/deploy/converters/DeployCloudFoundryServerGroupAtomicOperationConverter.java:19: error: package io.vavr does not exist
import static io.vavr.API.*;
                     ^
clouddriver/clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/client/retry/RetryInterceptor.java:21: error: cannot find symbol
import io.github.resilience4j.retry.IntervalFunction;
                                   ^
  symbol:   class IntervalFunction
  location: package io.github.resilience4j.retry
clouddriver/clouddriver-cloudfoundry/src/main/java/com/netflix/spinnaker/clouddriver/cloudfoundry/provider/agent/CloudFoundryServerGroupCachingAgent.java:45: error: package io.vavr.collection does not exist
import io.vavr.collection.HashMap;

```

added "io.github.resilience4j:resilience4j-vavr" dependency to clouddriver-cloudfoundry.gradle

Link:
https://github.com/resilience4j/resilience4j/pull/1537
https://github.com/resilience4j/resilience4j/issues/168
https://github.com/resilience4j/resilience4j/issues/1934#issuecomment-1842762828

Error:
```
> Task :clouddriver-kubernetes:compileTestJava
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:120: error: cannot find symbol
      assertThat(retryRegistry.getAllRetries().get(0).getName()).isEqualTo("mock-account");
                                              ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:123: error: cannot find symbol
      Retry.Metrics retryMetrics = retryRegistry.getAllRetries().get(0).getMetrics();
                                                                ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:285: error: cannot find symbol
    assertThat(retryRegistry.getAllRetries().get(0).getName()).isEqualTo("mock-account");
                                            ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:288: error: cannot find symbol
    Retry.Metrics retryMetrics = retryRegistry.getAllRetries().get(0).getMetrics();
                                                              ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:377: error: cannot find symbol
    assertThat(retryRegistry.getAllRetries().get(0).getName()).isEqualTo("mock-account");
                                            ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:380: error: cannot find symbol
    Retry.Metrics retryMetrics = retryRegistry.getAllRetries().get(0).getMetrics();
                                                              ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:450: error: cannot find symbol
    assertThat(retryRegistry.getAllRetries().get(0).getName()).isEqualTo("mock-account");
                                            ^
  symbol:   method get(int)
  location: interface Set<Retry>
clouddriver/clouddriver-kubernetes/src/test/java/com/netflix/spinnaker/clouddriver/kubernetes/op/job/KubectlJobExecutorTest.java:453: error: cannot find symbol
    Retry.Metrics retryMetrics = retryRegistry.getAllRetries().get(0).getMetrics();
                                                              ^
  symbol:   method get(int)
  location: interface Set<Retry>

```

As part of removing vavr dependency, resilience4j has made change that returns a Set instead of Seq when retryRegistry.getAllRetries() is called.
Link:
https://github.com/resilience4j/resilience4j/pull/1121/files#diff-f58a549005afee4cef1bdce1c1a5571f40fcede02013722f6bd05d221bde56eeR153
https://github.com/resilience4j/resilience4j/pull/1537

Reference:
https://github.com/resilience4j/resilience4j/pull/1537
https://github.com/resilience4j/resilience4j/issues/168
https://github.com/resilience4j/resilience4j/issues/1934#issuecomment-1842762828