refactor(jedis): adapting jedis4.
Springboot3 brings in jedis4 instead of jedis3.

In jedis4,
1. ScanParams and ScanResult classes are moved under appropriate packages so modified imports accordingly.

2. Jedis.zrangeByScore returns a list instead of a SET.

Errors:
```
clouddriver/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java:30: error: cannot find symbol
import redis.clients.jedis.ScanParams;
                          ^
  symbol:   class ScanParams
  location: package redis.clients.jedis
clouddriver/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/AbstractRedisCache.java:31: error: cannot find symbol
import redis.clients.jedis.ScanResult;
                          ^
  symbol:   class ScanResult

> Task :cats:cats-redis:compileGroovy FAILED
clouddriver/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cluster/ClusteredSortAgentScheduler.java:396: error: incompatible types: List<String> cannot be converted to Set<String>
      Set<String> oldKeys = jedis.zrangeByScore(WORKING_SET, "-inf", score(jedis, NOW));

```

Reference:
https://docs.spring.io/spring-boot/docs/3.0.x/reference/html/dependency-versions.html#appendix.dependency-versions
https://github.com/redis/jedis/blob/4.x/docs/3to4.md
https://github.com/redis/jedis/blob/4.x/docs/3to4-zset-list.md